name: Publish Electroneum Docker image

on:
    workflow_dispatch:
        inputs:
            ref:
                description: version to publish
                required: true
                type: string

env:
    DOCKER_USERNAME: sterliakov
    ORIG_IMAGE_NAME: electroneum

jobs:
    push_original:
        name: Push Electroneum Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
        -   uses: actions/checkout@v4
            with:
                repository: electroneum/electroneum-sc
                persist-credentials: false
                ref: ${{ inputs.ref }}
                token: ${{ secrets.MY_GITHUB_PAT }}

        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                cache-binary: false

        -   name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
                platforms: linux/amd64,linux/arm64
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ env.DOCKER_USERNAME }}/${{ env.ORIG_IMAGE_NAME }}:${{ inputs.ref }}
