name: Publish Electroneum Docker image

on:
    workflow_dispatch:
        inputs:
            ref:
                description: version to publish
                required: true
                type: string

env:
    DOCKER_USERNAME: sterliakov
    IMAGE_NAME: electroneum

jobs:
    push_to_registry:
        name: Push Electroneum Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
        -   name: Check out the repo
            uses: actions/checkout@v4
            with:
                repository: electroneum/electroneum-sc
                persist-credentials: false
                ref: ${{ inputs.ref }}
                token: ${{ secrets.MY_GITHUB_PAT }}

        -   name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Setup metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

        -   name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
